### PR TITLE
Add packer config

### PR DESCRIPTION
**Pull request by alexmuller**
These machines will be backed by Elastic Block Store (EBS) for use in EC2.

The source AMI is from https://cloud-images.ubuntu.com/locator/ec2/ and has the following properties:

- eu-west-1
- 14.04 LTS Trusty
- amd64
- [HVM (hardware virtual machine) instead of PV (paravirtual)][1]
  because more EC2 machine types seem to be available for HVM images

The name of the source AMI in the AWS console is: `ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-20160314`

[1]: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html

---

We've added a basic provisioning script which installs our version of Puppet onto the AMI.

We also install build-essential because it's required for lots of things (eg make) and is already present on all of our machines.

We should potentially use our APT mirror to install Puppet rather than adding a DEB from `apt.puppetlabs.com`.

### CODE REVIEW

**Comment by bazbremner** [comment]
You might be interested in the approach @joshmyers has taken in GOV.UK Pay's AMI build code to select the latest available upstream image so it doesn't take manual intervention to poke through the cloud-images output every time there's a release from Ubuntu.

Have a look at https://github.com/alphagov/pay-infra/blob/master/images/ami/lib/govuk-pay/ami_builder_helper.rb and I'm sure @joshmyers would be happy to answer any questions.

**Comment by mattbostock** [comment]
:+1: LGTM.

**Comment by deanwilson** [comment]
Looks fine to merge. Should we be using puppet 3.8 instead of puppet 3.6 now?

**Comment by alexmuller** [comment]
Good point, updated to use Puppet 3.8

**Comment by deanwilson** [comment]
Merge away.

**Pull request merged**
