### PR TITLE
Create bucket for whitehall attachments

### PR DESCRIPTION
**Pull request by surminus**
This is used to back-up whitehall attachments. 

Ticket: https://trello.com/c/DTByYmW1/51-sync-whitehall-attachments-to-s3
Related: https://github.com/alphagov/govuk-puppet/pull/4336

### CODE REVIEW

**Comment by alexmuller** [comment]
Updated this to rename the bucket from `govuk-whitehall-attachments` to `govuk-attachments` because it's going to take everything from `/mnt/uploads` on the asset-master machine, which includes asset-manager as well as whitehall. Hope that's ok!

**Comment by surminus** [comment]
Oh yeah, that completely makes sense and also two 🐦  one stone. Also need to update the job list in hiera :(

**Comment by deanwilson** [comment]
Just a note - `paired_user` allows public access to the buckets contents.

**Comment by alexmuller** [comment]
Good point! These attachments can't be public.

**Comment by surminus** [comment]
Paired with @deanwilson to create a different bucket

**Comment by deanwilson** [comment]
Looks fine. Merge away.

**Pull request merged**
