### PR TITLE
Modernize the README - there's now a Jenkins job to deploy changes

### PR DESCRIPTION
**Pull request by issyl0**
- Also, mention the 2ndline shared AWS account.

### CODE REVIEW

**Comment by surminus** [comment]
I think this is perfect for the README 👍 

However, I would still include how to run the commands manually in another doc somewhere, incase people want to run stuff on the test account, which we do not have a Jenkins job for. I know that @floehopper was running stuff from CLI for testing purposes, and it may be worth him having a read as the last person other than infrastructure to really look at this repo.

**Comment by issyl0** [comment]
@surminus I added a separate doc and slimmed down the README even more.

**Comment by chrisroos** [comment]
This looks good to me too, @issyl0. The only thought I have is that it might be worth linking to the new local-development-or-test-accounts.md doc from the README. What do you think?

**Comment by issyl0** [comment]
Thanks @chrisroos! Done.

**Pull request merged**
