### PR TITLE
govuk offsite assets

### PR DESCRIPTION
**Pull request by djsd123**
Provisions two S3 buckets that share the same policy.

https://trello.com/c/eGZsCDvm

### CODE REVIEW

**Comment by surminus** [comment]
I actually wouldn't be opposed to using the same bucket as the other offsite backups as that'd mean we could deploy quicker and have less admin (generating keys, add secrets etc). What do you think?

**Comment by djsd123** [comment]
I have no preference as the end result remains the same.  Yesterday, I briefly discussed with @deanwilson and he opted for separation.  I will modify to use existing resources.

**Comment by surminus** [comment]
Thanks! Sorry for conflicting opinions!

**Comment by djsd123** [comment]
@surminus Not a problem.

**Pull request closed without merging**
